name: 'Setup Gradle'
description: 'Setup JDK and Gradle'
inputs:
  cache-disabled:
    description: 'gradle.cache-disabled'
    default: 'false'
  cache-read-only:
    description: 'gradle.cache-read-only'
    default: 'true'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        # the latest listed version will be used for executions of Gradle
        java-version: |
          8
          11
          17
          21
    - uses: gradle/wrapper-validation-action@v2
    - uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-service-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-service-agree: "yes"

        cache-disabled: ${{ inputs.cache-disabled }}
        cache-read-only: ${{ inputs.cache-read-only }}

        gradle-home-cache-cleanup: true
