name: Build dev
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml
  publish:
    needs: [ test ]
    uses: ./.github/workflows/publish-snapshot.yml
    secrets: inherit
