name: Build Kotlin Matrix
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SAT"

jobs:
  build:
    name: Kotlin=${{ matrix.kotlin-version }}
    strategy:
      fail-fast: false
      matrix:
        kotlin-version: [
          '', # empty means a current project version
          '1.9.0-Beta',
          '[1.9.20-dev,1.9.20-dev-9999['
        ]
    uses: ./.github/workflows/run-tests.yml
    with:
      cache-disabled: true
      kotlin-version: ${{ matrix.kotlin-version }}
