name: Build TEST
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-gradle
      - uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: tests-publication
          arguments: build --continue
