name: Build branch
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - dev
      - kotlin-eap/*

jobs:
  compatibility-tests:
    uses: ./.github/workflows/run-tests-compatibility.yml

  compatibility-stress-tests:
    uses: ./.github/workflows/run-tests-compatibility-stress.yml
