name: Build main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy-website.yml
    permissions:
      contents: read
      pages: write
      id-token: write
