name: Build main
on:
  workflow_dispatch: # manual run
  schedule: # scheduled run every saturday
    - cron: '* * * * SAT'
  push:
    branches:
      - main

jobs:
  build:
    name: Kotlin ${{ matrix.kotlinVersionOverride }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest','macos-latest','windows-latest' ]
        kotlinVersion: [
          '1.8.10',
          '1.8.20-Beta',
          '[1.9.0-dev,1.9.0-dev-9999['
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            8
            11
            17
            19
      - name: Compile sources
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          arguments: |
            build
            -PskipTests
            -PskipLink
            -Pkotlin.override.version=${{ matrix.kotlinVersion }}
            --scan
            --continue
      - name: Link native binaries
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          arguments: |
            build
            -PskipTests
            -Pkotlin.override.version=${{ matrix.kotlinVersion }}
            --scan
            --continue
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          arguments: |
            build
            -Pkotlin.override.version=${{ matrix.kotlinVersion }}
            --scan
            --continue
