name: Build Kotlin Matrix
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SAT"

jobs:
  build:
    name: Kotlin=${{ matrix.kotlin-version }}
    strategy:
      fail-fast: false
      matrix:
        kotlin-version: [
          '', # empty means a current project version
          '1.9.0-Beta',
          '[1.9.0-RC,1.9.0-RC-9999['
          '[1.9.20-dev,1.9.20-dev-9999['
        ]
    uses: ./.github/workflows/run-tests.yml
    with:
      cache-disabled: true
      run-compatibility-tests: false
      kotlin-version: ${{ matrix.kotlin-version }}

  build-k2:
    name: Kotlin/K2=${{ matrix.kotlin-version }}
    strategy:
      fail-fast: false
      matrix:
        kotlin-version: [
          '1.9.0-Beta',
          '[1.9.0-RC,1.9.0-RC-9999['
          '[1.9.20-dev,1.9.20-dev-9999['
        ]
    uses: ./.github/workflows/run-tests.yml
    with:
      cache-disabled: true
      run-compatibility-tests: false
      kotlin-version: ${{ matrix.kotlin-version }}
      kotlin-use-k2: true

  build-cc:
    name: Kotlin/CC=${{ matrix.kotlin-version }}
    strategy:
      fail-fast: false
      matrix:
        kotlin-version: [
          '1.9.0-Beta',
          '[1.9.0-RC,1.9.0-RC-9999['
          '[1.9.20-dev,1.9.20-dev-9999['
        ]
    uses: ./.github/workflows/run-tests.yml
    with:
      cache-disabled: true
      run-compatibility-tests: false
      kotlin-version: ${{ matrix.kotlin-version }}
      configuration-cache-enabled: true
