name: Build main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml
  publish:
    needs: [ test ]
    uses: ./.github/workflows/publish-snapshot.yml
    secrets: inherit
  deploy:
    uses: ./.github/workflows/deploy-website.yml
    permissions:
      contents: read
      pages: write
      id-token: write
