name: Build dev
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  checks:
    uses: ./.github/workflows/run-checks.yml

  publish:
    needs: [ checks ]
    uses: ./.github/workflows/publish-snapshot.yml
    secrets: inherit
