name: Build Kotlin Matrix
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SAT"
  push:
    branches:
      - main

jobs:
  build:
    name: Kotlin ${{ matrix.kotlinVersion }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest','macos-latest','windows-latest' ]
        kotlinVersion: [
          '1.8.10',
          '1.8.20-RC',
          '[1.9.0-dev,1.9.0-dev-9999['
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-gradle

      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: mingw-w64-x86_64-openssl

      - name: Compile sources
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            -Pskip.test
            -Pskip.link
            -Pkotlin.override.version=${{ matrix.kotlinVersion }}
            --scan
            --continue
      - name: Link native binaries
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            -Pskip.test
            -Pkotlin.override.version=${{ matrix.kotlinVersion }}
            --scan
            --continue
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            -Pkotlin.override.version=${{ matrix.kotlinVersion }}
            --scan
            --continue
