name: Build release
on:
  push:
    tags:
      - '*'

jobs:
  checks:
    uses: ./.github/workflows/run-checks.yml

  publish:
    needs: [ checks ]
    uses: ./.github/workflows/publish-release.yml
    secrets: inherit

  publish-website:
    needs: [ publish ]
    uses: ./.github/workflows/publish-website.yml
    permissions:
      contents: read
      pages: write
      id-token: write
