name: Kotlin EAP CI
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        kotlin-version: [ '', '2.0.20-dev-+' ]
        try-next: [ 'true', 'false' ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
        with:
          cache-disabled: true

      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: mingw-w64-x86_64-openssl

      - run: ./gradlew build connectedCheck publishToMavenLocal --continue -Pckbuild.skipTests=true -Pckbuild.kotlinVersionOverride=${{ matrix.kotlin-version }} -Pkotlin.experimental.tryNext=${{ matrix.try-next }}
