name: Dependency Updates
on:
  workflow_dispatch: # manual run
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19

      - name: Run dependency updates
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          arguments: :dependencyUpdates --init-script gradle/libs.updates.gradle.kts --no-configure-on-demand
      - name: Write Job Summary
        uses: actions/github-script@v6
        with:
          script: |
            const { GITHUB_WORKSPACE } = process.env
            const { promises: fs } = require('fs')
            const summary = core.summary.addHeading('Dependency Updates Report')
            const globber = await glob.create('**/build/dependencyUpdates/report.txt')
            for await (const file of globber.globGenerator()) {
              const content = await fs.readFile(file, 'utf8')
              const f1 = file.slice(file.indexOf(GITHUB_WORKSPACE) + GITHUB_WORKSPACE.length + 1)
              const f2 = f1.slice(0, f1.indexOf('build/'))
              const name = f2.length ? f2 : 'root'
              summary.addDetails(name, content)
            }
            await summary.write()
