name: Publish snapshot
on: [ workflow_call ]

concurrency:
  group: publish-snapshot
  cancel-in-progress: false

jobs:
  publish:
    if: github.repository == 'whyoleg/cryptography-kotlin'
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
        with:
          cache-disabled: true

      - name: Publish to Maven Local (prepare packages)
        run: ./gradlew publishToMavenLocal -Pversion=0.3.0-SNAPSHOT --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.signingKey}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.signingPassword}}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.sonatypeUsername}}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.sonatypePassword}}

      - name: Publish snapshot to Sonatype
        run: ./gradlew publishAllPublicationsToSnapshotRepository -Pversion=0.3.0-SNAPSHOT --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.signingKey}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.signingPassword}}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.sonatypeUsername}}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.sonatypePassword}}
