name: Publish testing
on: [ workflow_call ]

jobs:
  publish:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
        with:
          cache-disabled: true

      - name: Publish to Maven Local (prepare packages)
        run: ./gradlew publishToMavenLocal --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.signingKey}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.signingPassword}}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.sonatypeUsername}}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.sonatypePassword}}

      - name: Publish signed packages to local directory
        run: ./gradlew publishAllPublicationsToProjectLocalRepository --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.signingKey}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.signingPassword}}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.sonatypeUsername}}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.sonatypePassword}}
