name: Run compatibility tests
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: compatibility-tests
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        target: [ 'jvmAll', 'js', 'native' ]
        include:
          - os: 'macos-latest'
            target: 'macos'
          - os: 'macos-latest'
            target: 'ios'
          - os: 'macos-latest'
            target: 'watchos'
          - os: 'macos-latest'
            target: 'tvos'
          - os: 'windows-latest'
            target: 'native'
          - os: 'macos-latest'
            target: 'connectedAndroid'
            android-api-level: 21
          - os: 'macos-latest'
            target: 'connectedAndroid'
            android-api-level: 27
          - os: 'macos-latest'
            target: 'connectedAndroid'
            android-api-level: 33
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
        with:
          cache-read-only: true

      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: mingw-w64-x86_64-openssl

      - name: Run tests
        if: ${{ matrix.target != 'connectedAndroid' }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.target }}ProviderTest -Pckbuild.providerTests.step=compatibility.generate -Ptesttool.instanceId=${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }} --continue

      - name: Run tests (android)
        if: ${{ matrix.target == 'connectedAndroid' }}
        uses: ./.github/actions/run-android-emulator-tests
        with:
          api-level: ${{ matrix.android-api-level }}
          test-reports-classifier: 'compatibility-generate'
          arguments: ${{ matrix.target }}ProviderTest -Pckbuild.providerTests.step=compatibility.generate -Ptesttool.instanceId=${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }} --continue

      - name: Dump testtool server-storage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            dumpTesttoolServerStorage
            -Ptesttool.instanceId=${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }}
      - name: Upload testtool server-storage dump
        uses: actions/upload-artifact@v3
        with:
          name: compatibility-tests-data
          path: build/testtool/server-storage-dump
          if-no-files-found: error

  validate:
    needs: [ generate ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        target: [ 'jvmAll', 'js', 'native' ]
        include:
          - os: 'macos-latest'
            target: 'macos'
          - os: 'macos-latest'
            target: 'ios'
          - os: 'macos-latest'
            target: 'watchos'
          - os: 'macos-latest'
            target: 'tvos'
          - os: 'windows-latest'
            target: 'native'
          - os: 'macos-latest'
            target: 'connectedAndroid'
            android-api-level: 21
          - os: 'macos-latest'
            target: 'connectedAndroid'
            android-api-level: 27
          - os: 'macos-latest'
            target: 'connectedAndroid'
            android-api-level: 33
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
        with:
          cache-read-only: true

      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: mingw-w64-x86_64-openssl

      - name: Download testtool server-storage dump
        uses: actions/download-artifact@v3
        with:
          name: compatibility-tests-data
          path: build/testtool/server-storage-dump

      - name: Restore testtool server-storage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: restoreTesttoolServerStorage

      - name: Run tests
        if: ${{ matrix.target != 'connectedAndroid' }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.target }}ProviderTest -Pckbuild.providerTests.step=compatibility.validate -Ptesttool.instanceId=${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }} --continue

      - name: Run tests (android)
        if: ${{ matrix.target == 'connectedAndroid' }}
        uses: ./.github/actions/run-android-emulator-tests
        with:
          api-level: ${{ matrix.android-api-level }}
          test-reports-classifier: 'compatibility-validate'
          arguments: ${{ matrix.target }}ProviderTest -Pckbuild.providerTests.step=compatibility.validate -Ptesttool.instanceId=${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }} --continue
