name: Build website
on:
  workflow_dispatch:
  workflow_call:

jobs:
  website:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - uses: ./.github/actions/setup-gradle
        with:
          cache-disabled: true
      - name: Build documentation
        uses: gradle/gradle-build-action@v2
        with:
          arguments: mkdocsBuild --no-configuration-cache
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: site
