name: Run compatibility tests
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: compatibility-tests
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  tests-compatibility-generate:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        target: [ 'jvmAll', 'js', 'native' ]
        include:
          - os: 'macos-14'
            target: 'macos'
          - os: 'macos-14'
            target: 'ios'
          - os: 'macos-14'
            target: 'watchos'
          - os: 'macos-14'
            target: 'tvos'
          - os: 'windows-latest'
            target: 'native'
          - os: 'ubuntu-latest'
            target: 'connectedAndroid'
            android-api-level: 21
          - os: 'ubuntu-latest'
            target: 'connectedAndroid'
            android-api-level: 27
          - os: 'ubuntu-latest'
            target: 'connectedAndroid'
            android-api-level: 33
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle

      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: mingw-w64-x86_64-openssl

      - name: Run tests
        if: ${{ matrix.target != 'connectedAndroid' }}
        run: ./gradlew ${{ matrix.target }}ProviderTest -Pckbuild.providerTests.step=compatibility.generate -Pckbuild.testtool.instanceId=${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }} --continue

      - name: Run tests (android)
        if: ${{ matrix.target == 'connectedAndroid' }}
        uses: ./.github/actions/run-android-emulator-tests
        with:
          api-level: ${{ matrix.android-api-level }}
          test-reports-classifier: 'compatibility-generate'
          run: ./gradlew ${{ matrix.target }}ProviderTest -Pckbuild.providerTests.step=compatibility.generate -Pckbuild.testtool.instanceId=${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }} --continue

      - name: Dump testtool server-storage
        run: tar -cf ${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }}.tar build/testtool/server-storage
      - name: Upload testtool server-storage
        uses: actions/upload-artifact@v4
        with:
          name: compatibility-tests-data-${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }}
          path: ${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }}.tar
          if-no-files-found: error

  tests-compatibility-validate:
    needs: [ tests-compatibility-generate ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        target: [ 'jvmAll', 'js', 'native' ]
        include:
          - os: 'macos-14'
            target: 'macos'
          - os: 'macos-14'
            target: 'ios'
          - os: 'macos-14'
            target: 'watchos'
          - os: 'macos-14'
            target: 'tvos'
          - os: 'windows-latest'
            target: 'native'
          - os: 'ubuntu-latest'
            target: 'connectedAndroid'
            android-api-level: 21
          - os: 'ubuntu-latest'
            target: 'connectedAndroid'
            android-api-level: 27
          - os: 'ubuntu-latest'
            target: 'connectedAndroid'
            android-api-level: 33
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle

      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: mingw-w64-x86_64-openssl

      - name: Download testtool server-storage
        uses: actions/download-artifact@v4
        with:
          pattern: compatibility-tests-data-*
          merge-multiple: true
      - name: Restore testtool server-storage
        run: for file in *.tar; do tar -xf "$file"; done
      - name: Delete downloaded testtool server-storage
        run: rm *.tar

      - name: Run tests
        if: ${{ matrix.target != 'connectedAndroid' }}
        run: ./gradlew ${{ matrix.target }}ProviderTest -Pckbuild.providerTests.step=compatibility.validate -Pckbuild.testtool.instanceId=${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }} --continue

      - name: Run tests (android)
        if: ${{ matrix.target == 'connectedAndroid' }}
        uses: ./.github/actions/run-android-emulator-tests
        with:
          api-level: ${{ matrix.android-api-level }}
          test-reports-classifier: 'compatibility-validate'
          run: ./gradlew ${{ matrix.target }}ProviderTest -Pckbuild.providerTests.step=compatibility.validate -Pckbuild.testtool.instanceId=${{ matrix.os }}-${{ matrix.target }}-${{ matrix.android-api-level }} --continue
